# Generated by Django 6.0.3 on 2026-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_telemetry_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('radio_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
            ],
        ),
    ]
